language: node_js
node_js:
- 10
install:
- npm install
- npm install -g codecov
script:
- npm run build
- npm test
after_success:
- codecov
deploy:
  provider: npm
  cleanup: false
  edge: true
  email: aleksandryackovlev@yandex.ru
  on:
    tags: true
    repo: aleksandryackovlev/openapi-mock-express-middleware
  api_key:
    secure: yQoDpieXiMk0+XyiYPkoJugmxaZDpJB5CnsSUGLp6kDEj0OiEJMU05T42cp+7ylElGYS3maq7DG+AO7vO1j4VfVr+7qXVDyr1xlM50Bz43YBxOd9SuRwiYIFRisWEQLelgXgcK1/7xAXQgUlumyBj2vnx8wjIkQIA0d2Dffo5jGG6YGrC4cuz/RY5Hn7uys5DaJDUhUgHZ3FYUjtQkk9egEaIm1fdQ+TNhsbF4TjrKVjNsjIShO2fXZ02SAf33KyYJ+2NCcOUjVDTFma2hiaYWMSVt1czDvl1exVmMhaY/F9DugOm23bSqSppCyuoAyVPJwDoAi13zuPEIAoNi6QYqyerEewAhUMI/3mWbJZa/Upri5p8afhc6ICdnEReSnmuEzBVlckx51ZuCTP9D9jMhRJmG1fyiFPHmV9fQTKXcupH2ve2I96kRq/pxdficX8/utEjJXyH+/1jIjgdNl5T/s3qv5wqh2X3BjQuTDQkIk1//Q+4H58qyiRX670R0lp4ffYBg6xYD01imSaF7or6q2Q2ZmA47v+GNaUflHWvcbP9g/uRiC+ZV9IC1t1G81P1gcEi5qrk4ky6GIvva/HfIBZocjIfX+dA//Wpr7zdJ/TmfQOhxuzoAOn9xLCogCMUWJ9qin6EcPMdYt837eRn7rgwkC8x3IKh7jFwDjZJUQ=
